<header>
        <div class="logo">
            <a href="index.php">
            <img src="file/image/ewallet.png" alt="logo"></a>
            <a href="index.php">UniCoin</a>
        </div>
        <ul>
            <li><a href="About.php">About</a></li>
            <li><a href="Service.php">Service</a></li>
            <li></li>
            <li><a href="login.php">Log in</a></li>
            <li><a href="signup.php">Sign Up</a></li>
        </ul>
</header>